---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: opa
  namespace: opa
spec:
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: opa
    version: "1.13.4"
  values:
    image: openpolicyagent/opa
    imageTag: "0.18.0"
    replicas: 1
    timeoutSeconds: 5
    opa: null
    admissionControllerNamespaceSelector:
      matchExpressions:
        - {key: openpolicyagent.org/webhook, operator: In, values: [enable]}
    authz:
      enabled: false
    mgmt:
      image: openpolicyagent/kube-mgmt
      imageTag: "0.11"
      configmapPolicies:
        enabled: true
        namespaces:
          - opa
        requireLabel: true
