---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
spec:
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: prometheus-operator
    version: "9.3.1"
  values:
    prometheusOperator:
      tlsProxy:
        image:
          repository: squareup/ghostunnel
          tag: v1.5.2

      admissionWebhooks:
        patch:
          image:
            repository: jettech/kube-webhook-certgen
            tag: v1.2.1
    
      image:
        repository: quay.io/coreos/prometheus-operator
        tag: v0.38.1

      configmapReloadImage:
        repository: docker.io/jimmidyson/configmap-reload
        tag: v0.3.0

      prometheusConfigReloaderImage:
        repository: quay.io/coreos/prometheus-config-reloader
        tag: v0.38.1

      hyperkubeImage:
        repository: k8s.gcr.io/hyperkube
        tag: v1.16.12

    prometheus:
      prometheusSpec:
        image:
          repository: quay.io/prometheus/prometheus
          tag: v2.18.2

    alertmanager:
      enabled: true
      config:
        global:
          smtp_smarthost: in-v3.mailjet.com:587
          smtp_from: CHANGE_ME
          smtp_auth_username: CHANGED_THROUGH_SEALEDSECRET
          smtp_auth_password: CHANGED_THROUGH_SEALEDSECRET
        reveivers:
        - name: 'Null'
          email_configs:
          - to: CHANGED_THROUGH_SEALEDSECRET # Will be overwritten by alertmanager.yaml sealed secret
      #config:
      #  receivers:
      #  - name: prometheus-msteams
      #    webhook_configs:
      #    - url: "http://prometheus-msteams:2000/alertmanager"
      #      send_resolved: true
      #  route:
      #    group_by:
      #    - job
      #    group_interval: 5m
      #    group_wait: 30s
      #    receiver: prometheus-msteams
      #    repeat_interval: 12h
      #    routes:
      #    - match:
      #        alertname: Watchdog
      #      receiver: prometheus-msteams
      alertmanagerSpec:
        useExistingSecret: true
        image:
          repository: quay.io/prometheus/alertmanager
          tag: v0.21.0

    grafana:
      admin:
        existingSecret: "grafana-admin-auth"
        userKey: admin-user
        passwordKey: admin-password

      image:
        repository: grafana/grafana
        tag: "7.1.1"

      downloadDashboardsImage:
        repository: curlimages/curl
        tag: "7.70.0"

      initChownData:
        image:
          repository: busybox
          tag: "1.31.1"
      
      sidecar:
        image:
          repository: kiwigrid/k8s-sidecar
          tag: "0.1.151"

    kube-state-metrics:
      image:
        repository: quay.io/coreos/kube-state-metrics
        tag: v1.9.7

    prometheus-node-exporter:
      image:
        repository: quay.io/prometheus/node-exporter
        tag: v1.0.1      
