###########################################################
# https://github.com/fluxcd/flux/tree/master/chart/flux
###########################################################
git:
  url: git@github.com:digiwhite1980/flux
  branch: master
  path: "clusters/lab/main,teams/lab/main"
  pollInterval: 1m
  # secretName: flux-ssh
  # secretDataKey: deploy-key

sync:
  state: secret

registry:
  disableScanning: true

syncGarbageCollection:
  enabled: true

manifestGeneration: true

image:
  repository: docker.io/fluxcd/flux
  tag: 1.20.2

# extraVolumeMounts:
#   - name: istio-volume
#     mountPath: /tmp/istio

# extraVolumes:
#   - name: istio-volume
#     emptyDir: {}

# initContainers:
#   install-istio:
#     image: "istio/istioctl:1.5.1"
#     imagePullPolicy: "IfNotPresent"
#     command: ['sh', '-c', 'cp /usr/local/bin/istioctl /tmp/istio/']
#     volumeMounts:
#       - mountPath: /tmp/istio
#         name: istio-volume
