resources:
  - ../../../bases/team-default
  - ../../../bases/flux

namespace: team-2

patches:
- target:
    kind: Namespace
  patch: |-
    - op: replace
      path: /metadata/name
      value: team-2

patchesStrategicMerge:
- patch-flux.yaml
