apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbac-team
  namespace: PLACEHOLDER
subjects:
- kind: ServiceAccount
  name: team
# - kind: Group
#   name: system:serviceaccounts:team
#   apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: rbac-team
  apiGroup: rbac.authorization.k8s.io
