apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-deployment
  namespace: team-1
spec:
  selector:
    matchLabels:
      app: alpine
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: alpine
    spec:
      securityContext:
        fsGroup: 1024    
      containers:
      - name: alpine
        image: alpine
        command: [ "/bin/sh" ]
        args: [ "-c", "while true; do sleep 3600; done" ]
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          runAsUser: 1024
          runAsGroup: 1024
          readOnlyRootFilesystem: true