apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus-comunity
  namespace: monitoring
spec:
  url: https://prometheus-community.github.io/helm-charts
  interval: 1m
