apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus-comunity
  namespace: monitoring
spec:
  url: https://prometheus-community.github.io/helm-charts
  interval: 1m
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kube-state-metrics
  namespace: monitoring
spec:
  url: https://charts.helm.sh/stable
  interval: 1m
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: grafana
  namespace: monitoring
spec:
  url: https://grafana.github.io/helm-charts
  interval: 1m
