apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: scp-system
spec:
  interval: 2m
  releaseName: kube-state-metrics
  targetNamespace: monitoring
  chart:
    spec:
      chart: kube-state-metrics
      version: 1.2.4
      sourceRef:
        kind: HelmRepository
        name: kube-state-metrics
        namespace: scp-system
  values:
