---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sealed-secrets
spec:
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: sealed-secrets
    version: "v0.12.4"
  values:  # https://hub.helm.sh/charts/fluxcd/flux
    namespace: sealed-secrets
    secretName: ss-default
