apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbac-team
  namespace: flux-teams
subjects:
 - kind: Group
   name: system:serviceaccounts:flux-teams
   apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: rbac-team
  apiGroup: rbac.authorization.k8s.io