resources:
  - ../../../../bases/team-default
  - ../../../../bases/flux

namespace: team-1

patches:
- target:
    kind: Namespace
    labelSelector: namespace-type=team
  patch: |-
    - op: replace
      path: /metadata/name
      value: team-1
    - op: replace
      path: /metadata/labels/scp.gatekeeper	  
      value: restricted     
# - target: 
#     kind: ServiceAccount
#     namespace: flux-teams
#   patch: |-
#     - op: replace
#       path: /metadata/name
#       value: flux-team-1

#- target:
#    labelSelector: "type=gatekeeper-constraint"
#  patch: |-
#    - op: replace
#      path: /spec/match/namespaces
#      value: [ team-1 ]
#    - op: replace
#      path: /metadata/name
#      value: team-1

patchesStrategicMerge:
- patch-flux.yaml
