resources:
  - ../../../bases/team-default
  - ../../../bases/flux

namespace: team-3

patches:
- target:
    kind: Namespace
  patch: |-
    - op: replace
      path: /metadata/name
      value: team-3
- target:
    labelSelector: "type=gatekeeper-constraint"
  patch: |-
    - op: replace
      path: /spec/match/namespaces
      value: [ team-3 ]
    - op: replace
      path: /metadata/name
      value: team-3

patchesStrategicMerge:
- patch-flux.yaml
