resources:
  - ../../../bases/team-default
  - ../../../bases/flux

namespace: team-1

patches:
- target:
    kind: Namespace
  patch: |-
    - op: replace
      path: /metadata/name
      value: team-1
- target:
    kind: K8sPSPReadOnlyRootFilesystem
  patch: |-
    - op: replace
      path: /spec/match/namespaces
      value: [ team-1 ]
- target:
    kind: K8sPSPCapabilities
  patch: |-
    - op: replace
      path: /spec/match/namespaces
      value: [ team-1 ]

patchesStrategicMerge:
- patch-flux.yaml
