resources:
  - ../../../bases/team-default
  - ../../../bases/flux

namespace: team-1

patches:
- target:
    kind: Namespace
  patch: |-
    - op: replace
      path: /metadata/name
      value: team-1

##############################################################
# We target all objects with label type=gatekeeper-constraint
##############################################################
- target:
    labelSelector: "type=gatekeeper-constraint"
  patch: |-
    - op: replace
      path: /spec/match/namespaces
      value: [ team-1 ]

patchesStrategicMerge:
- patch-flux.yaml
