apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux
spec:
  values:
    git:
      url: git@github.com:digiwhite1980/flux
      path: "deployments/team_1"
    allowedNamespaces:
    - team-1
