allowedNamespaces: 
- team-1
clusterRole:
  create: false
git:
  branch: master
  path: deployments/team-1
  pollInterval: 1m
  readonly: true
  url: git@github.com:digiwhite1980/flux
  #secretName: team-1
  #secretDataKey: deploy-key
image:
  repository: docker.io/fluxcd/flux
  tag: 1.20.2
manifestGeneration: false
rbac:
  create: false
registry:
  disableScanning: true
serviceAccount:
  create: true
  name: flux-team-1
sync:
  state: secret
syncGarbageCollection:
  enabled: true
